#!/bin/bash

# Afficher le menu et capturer la sélection
selection=$(echo -e "  Configuration Sway\n󰋊  Disques\n󰸉  Fond d'écran\n󱔓  Panneau\n󰤥  Réseau\n  Son\n󱥚  Thème"| rofi -dmenu -config ~/.config/rofi/menu-config.rasi)

# Vérifier si une sélection a été faite
if [[ -n "$selection" ]]; then
    case "$selection" in
		"  Configuration Sway")
			foot --hold yazi ~/.config/sway/config.d
			;;
		"󰋊  Disques")
			gnome-disks
			;;
		"󰸉  Fond d'écran")
			~/.config/rofi/scripts/wallpaper-menu
			;;
		"󱔓  Panneau")
			foot --hold yazi ~/.config/waybar
			;;
		"󰤥  Réseau")
			nm-connection-editor
			;;
		"  Son")
			pavucontrol
			;;
		"󱥚  Thème")
			nwg-look
			;;
    esac
fi   
