# Environnement
exec dbus-update-activation-environment --systemd WAYLAND_DISPLAY 

exec dbus-run-session -- pipewire &
exec dbus-run-session -- wireplumber &
exec dbus-run-session -- pipewire-pulse &

# Services système
exec /usr/libexec/xfce-polkit
exec wl-paste --watch cliphist store

# Utilitaires
exec gammastep   
exec mako

# Tiling
exec autotiling &
