# Applications favorites
bindsym $mod+Return exec $term
bindsym $mod+e exec $filemanager
bindsym $mod+d exec $menu
bindsym $mod+w exec $texteditor

# Fenêtres & focus
bindsym $mod+q kill
bindsym $mod+f fullscreen
bindsym $mod+space floating toggle

bindsym $mod+Left focus left
bindsym $mod+Down focus down
bindsym $mod+Up focus up
bindsym $mod+Right focus right

bindsym $mod+Shift+Left move left
bindsym $mod+Shift+Down move down
bindsym $mod+Shift+Up move up
bindsym $mod+Shift+Right move right

# Programmes
bindsym $mod+y exec foot -e yazi
bindsym $mod+i exec foot -e yazi Info
bindsym $mod+Shift+f exec foot --hold fastfetch
bindsym $mod+n exec nm-connection-editor

# Rofi
bindsym $mod+a exec ~/.config/rofi/scripts/alarm-window
bindsym $mod+s exec ~/.config/rofi/scripts/system-menu
bindsym $mod+g exec ~/.config/sway/scripts/guitar
bindsym $mod+h exec ~/.config/rofi/scripts/show-keybinding
bindsym $mod+c exec ~/.config/sway/scripts/config-menu
bindsym $mod+v exec cliphist list | rofi -dmenu -p "󰏢 Clipboard" -config .config/rofi/clipboard.rasi | cliphist decode | wl-copy
bindsym $mod+b exec ~/.config/rofi/scripts/web-menu
bindsym $mod+p exec ~/.config/sway/scripts/powermenu
bindsym $mod+Shift+r exec ~/.config/sway/scripts/rand-wallpaper
bindsym $mod+Shift+b exec ~/.config/rofi/scripts/bookmarks

# Système
bindsym $mod+Escape exec foot --hold btop
bindsym $mod+r reload
bindsym $mod+u exec foot -e sh -c "flatpak update && sudo xbps-install -Syu; pkill -SIGRTMIN+1 WAYBAR; \$SHELL"

# Touches spéciales
bindsym XF86HomePage exec $web
bindsym XF86Tools exec aimp
bindsym XF86Mail exec thunderbird
bindsym XF86Messenger exec discord
bindsym Print exec flameshot gui
bindsym XF86Calculator exec galculator

# Volume
bindsym --locked XF86AudioRaiseVolume exec wpctl set-volume @DEFAULT_SINK@ 5%+
bindsym --locked XF86AudioLowerVolume exec wpctl set-volume @DEFAULT_SINK@ 5%-
bindsym --locked XF86AudioMute exec wpctl set-mute @DEFAULT_SINK@ toggle
bindsym --locked XF86AudioMicMute exec wpctl set-mute @DEFAULT_SOURCE@ toggle 

# Workspaces
bindsym $mod+ampersand workspace number 1
bindsym $mod+eacute workspace number 2
bindsym $mod+quotedbl workspace number 3

bindsym $mod+shift+ampersand move container to workspace 1
bindsym $mod+shift+eacute move container to workspace 2
bindsym $mod+shift+quotedbl move container to workspace 3
