for_window [app_id="flameshot"] floating enable
for_window [app_id="galculator"] floating enable
for_window [app_id="io.gitlab.adhami3310.Impression"] floating enable
for_window [app_id="nm-connection-editor"] floating enable
for_window [app_id="nwg-look"] floating enable
for_window [app_id="pavucontrol"] floating enable
for_window [app_id="polkit-gnome-authentication-agent-1"] floating enable
for_window [class="steam" title="Liste de contacts"] floating enable
for_window [app_id="thunar" title="Confirmer le remplacement des fichiers"] floating enable
for_window [app_id="thunar" title="Opération sur des fichiers en cours"] floating enable
for_window [app_id="thunar" title="Renommer"] floating enable
for_window [app_id="xarchiver"] floating enable
for_window [app_id="xdg-desktop-portal-gtk"] resize set width 800 height 550
