# Appearance & FX
gaps inner 8
default_border pixel 3
default_floating_border pixel 3
default_orientation auto
smart_borders on

# Catppuccin Colors
# target                 title     bg    text   indicator  border
client.focused           $teal     $base $text  $teal      $teal
client.focused_inactive  $overlay0 $base $text  $overlay0  $overlay0
client.unfocused         $overlay0 $base $text  $overlay0  $overlay0
client.urgent            $peach	   $base $peach $overlay0  $peach
client.placeholder       $overlay0 $base $text  $overlay0  $overlay0
client.background        $base

set $gnome-schema org.gnome.desktop.interface
exec_always {gsettings set $gnome-schema cursor-theme "Breeze_Light"}   
