#!/bin/bash

set -euo pipefail 

VERT='\033[0;32m'
JAUNE='\033[1;33m'
NC='\033[0m'

echo -e "${VERT}=== Script de désactivation de libvirt ===${NC}"
echo

echo -e "${JAUNE}>>> Désactivation du service...${NC}"
sudo sv stop libvirtd
sudo rm /var/service/libvirtd
echo

echo -e "${JAUNE}>>> Désinstallation de gnome-boxes...${NC}"
sudo xbps-remove -Ry gnome-boxes
echo

echo -e "${JAUNE}>>> Nettoyage...${NC}"
rm -r ~/.cache/gnome-boxes ~/.cache/libvirt
rm -r ~/.config/gnome-boxes ~/.config/libvirt
rm -r ~/.local/share/gnome-boxes
sudo rm -r /etc/libvirt
echo

echo -e "${VERT}=== Virtualisation desactivée ===${NC}"
echo
