#!/bin/bash

options="VoidDocs\0icon\x1fvoid-logo-notext
BraveSearch\0icon\x1fbrave
Movix\0icon\x1fcom.github.artemanufrij.playmyvideos
ProtonDB\0icon\x1fdistributor-logo-steamos
Twitch\0icon\x1ftwitch-indicator
Youtube\0icon\x1fyoutube"

selection=$(echo -e "$options" | rofi -dmenu -show-icons -icon-theme "Papirus" -config ~/.config/rofi/web-menu.rasi)

if [[ -n "$selection" ]]; then
    case "$selection" in
		"VoidDocs")
   			brave-origin-nightly https://docs.voidlinux.org/
   			;;
   		"BraveSearch")
   		   	brave-origin-nightly https://search.brave.com 
   		   	 ;;  
		"Movix")
			firefox https://movix.bet
			;;
        "ProtonDB")
            brave-origin-nightly https://www.protondb.com
            ;;
		"Twitch")
			firefox https://www.twitch.tv/directory
            ;;
        "Youtube")                    
            brave-origin-nightly https://www.youtube.com
             ;; 
    esac
fi   
