# Applications favorites
bind=SUPER,Return,spawn,foot
bind=SUPER,e,spawn,thunar
bind=SUPER,d,spawn,rofi -show drun -config $HOME/.config/rofi/applications-menu.rasi 
bind=SUPER,code:52,spawn,foot -e micro

# Fenêtres/focus
bind=SUPER,f,togglefullscreen
bind=SUPER,code:38,killclient,
bind=SUPER,space,togglefloating

bind=SUPER,Left,focusdir,left
bind=SUPER,Right,focusdir,right
bind=SUPER,Up,focusdir,up
bind=SUPER,Down,focusdir,down   

bind=SUPER+Shift,Up,exchange_client,Up
bind=SUPER+Shift,Right,exchange_client,Right
bind=SUPER+Shift,Down,exchange_client,Down
bind=SUPER+Shift,Left,exchange_client,Left

# Layouts
circle_layout=tile,scroller,dwindle
bind=SUPER,t,setlayout,dwindle
bind=SUPER,l,switch_layout

# Programmes
bind=SUPER,y,spawn,foot -e yazi
bind=SUPER,i,spawn,foot -e yazi Info
bind=SUPER+Shift,p,spawn,pavucontrol
bind=SUPER+Shift,s,spawn,steam
bind=SUPER+Shift,f,spawn,foot --hold fastfetch
bind=SUPER+Shift,h,spawn,hyprpicker
bind=SUPER,code:47,spawn,gnome-boxes
bind=SUPER+Shift,c,spawn,foot -e calcurse

# Rofi
bind=SUPER,code:24,spawn,$HOME/.config/rofi/scripts/alarm-window
bind=SUPER+Shift,code:24,spawn,$HOME/.config/rofi/scripts/show-alias
bind=SUPER,p,spawn,$HOME/.config/mango/scripts/powermenu
bind=SUPER,s,spawn,$HOME/.config/rofi/scripts/system-menu
bind=SUPER+Shift,d,spawn,rofi -show drun -config $HOME/.config/rofi/gnome-menu.rasi 
bind=SUPER,g,spawn,$HOME/.config/sway/scripts/guitar
bind=SUPER,h,spawn,$HOME/.config/rofi/scripts/show-keybinding
bind=SUPER+SHIFT,l,spawn,$HOME/.config/mango/scripts/layouts
bind=SUPER+SHIFT,code:52,spawn,$HOME/.config/rofi/scripts/wallpaper-menu
bind=SUPER,c,spawn,$HOME/.config/mango/scripts/config-menu
bind=SUPER,v,spawn_shell,cliphist list | rofi -dmenu -p "󰏢 Clipboard" -config .config/rofi/clipboard.rasi | cliphist decode | wl-copy
bind=SUPER,b,spawn,$HOME/.config/rofi/scripts/web-menu

# Système
bind=SUPER,Escape,spawn,foot -e btop
bind=SUPER,r,reload_config
bind=SUPER+Shift,r,spawn,$HOME/.config/mango/waybar/scripts/reload
bind=SUPER,u,spawn,foot -e sh -c "sudo xbps-install -Syu; exec \$SHELL"

# Touches spéciales
bind=NONE,XF86HomePage,spawn,firefox
bind=NONE,XF86Tools,spawn,lollypop
bind=NONE,XF86Mail,spawn,thunderbird
bind=NONE,XF86Messenger,spawn,discord
bind=NONE,Print,spawn,flameshot gui
bind=NONE,XF86Calculator,spawn,galculator

# Volume
bind=NONE,XF86AudioRaiseVolume,spawn,wpctl set-volume @DEFAULT_SINK@ 5%+
bind=NONE,XF86AudioLowerVolume,spawn,wpctl set-volume @DEFAULT_SINK@ 5%-
bind=NONE,XF86AudioMute,spawn,wpctl set-mute @DEFAULT_SINK@ toggle
bind=SHIFT,XF86AudioMute,spawn,wpctl set-mute @DEFAULT_SOURCE@ toggle

# Workspaces
bind=SUPER,1,view,1
bind=SUPER,2,view,2
bind=SUPER,3,view,3

bind=SUPER+SHIFT,1,tag,1
bind=SUPER+SHIFT,2,tag,2
bind=SUPER+SHIFT,3,tag,3

bind=SUPER+Ctrl,Left,tagtoleft
bind=SUPER+Ctrl,Right,tagtoright
