windowrule=appid:galculator,isfloating:1
windowrule=appid:io.gitlab.adhami3310.Impression,title:Impression,isfloating:1
windowrule=appid:nm-connection-editor,isfloating:1
windowrule=appid:nwg-look,isfloating:1
windowrule=appid:pavucontrol,isfloating:1
windowrule=appid:steam,title:Liste de contacts,isfloating:1,width:500,height:700
windowrule=appid:thunar,title:Confirmer*,isfloating:1
windowrule=appid:thunar,title:Opération*,isfloating:1
windowrule=appid:thunar,title:Renommer*,isfloating:1
windowrule=appid:timeshift-gtk,isfloating:1
windowrule=appid:xarchiver,isfloating:1
windowrule=appid:xdg-desktop-portal-gtk,isfloating:1
windowrule=appid:xfce-polkit,isfloating:1
